### ISSUE TITLE
bug: data is not cleared after tests for `Method.Each`

### ISSUE THREAD

**Issue by dan-online** [josh-development/utilities#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

The data from `Method.Each` are left in the database at the end of the tests defined [here](https://github.com/josh-development/utilities/blob/4d2b099be6743f8e717babddaa52f558af896f6c/packages/provider/src/tests/runProviderTest.ts#L1779-L1802)

### Steps To Reproduce

Run the tests on a provider

### Expected behavior

The provider database should be empty on finish of the tests

**Comment by RealShadowNova** [comment]
I can confirm that data from the tests for `Method.Each` are left and not cleared after the test is complete.

This is the data from `@joshdb/json` after it's tests are ran:
```json
{"test:each1":"value1","test:each2":"value2","test:each3":"value3"}
```
